doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            User:
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/User/Infrastructure/Doctrine/Entities'
                prefix: 'App\Modules\User\Infrastructure\Doctrine\Entities'
                is_bundle: false
            Task:
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/Task/Infrastructure/Doctrine/Entities'
                prefix: 'App\Modules\Task\Infrastructure\Doctrine\Entities'
                is_bundle: false
            Project:
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/Project/Infrastructure/Doctrine/Entities'
                prefix: 'App\Modules\Project\Infrastructure\Doctrine\Entities'
                is_bundle: false
            Employee:
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/Employee/Infrastructure/Doctrine/Entities'
                prefix: 'App\Modules\Employee\Infrastructure\Doctrine\Entities'
                is_bundle: false
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
